// Generated by CoffeeScript 1.6.3
(function() {
  var $, TestFrontend, WebRtcTest, juery;

  WebRtcTest = require('./webrtc_test').WebRtcTest;

  $ = juery = require('jquery');

  TestFrontend = (function() {
    function TestFrontend() {
      this.$title = $('#title');
      this.$prompt = $('#prompt');
      this.$video = $('#video');
      this.$input = $('#input');
      if (!this.$title || !this.$prompt || !this.$video || !this.$input) {
        console.log("Incomplete frontend!");
      }
    }

    TestFrontend.prototype.clear = function() {
      this.$title.empty();
      this.$prompt.empty();
      this.$video.empty();
      return this.$input.empty();
    };

    TestFrontend.prototype.clear_video = function() {
      return this.$video.empty();
    };

    TestFrontend.prototype.clear_input = function() {
      return this.$input.empty();
    };

    TestFrontend.prototype.title = function(text) {
      return this.$title.text(text);
    };

    TestFrontend.prototype.prompt = function(text) {
      return this.$prompt.text(text);
    };

    TestFrontend.prototype.prompt_html = function(html) {
      return this.$prompt.html(html);
    };

    TestFrontend.prototype.video = function(stream) {};

    TestFrontend.prototype.add_button = function(text, cb) {
      var dom;
      dom = $('<button></button>').text(text);
      dom.click(cb);
      return this.$input.append(dom);
    };

    return TestFrontend;

  })();

  $(function() {
    var frontend, test;
    frontend = new TestFrontend($('body'));
    return test = new WebRtcTest(frontend, function(err) {
      return console.log(err);
    });
  });

}).call(this);
